### PR TITLE
[Chord type] - Fixed typo in README

### PR DESCRIPTION
**Pull request by AdrienFromToulouse**

### CODE REVIEW

**Comment by danigb** [comment]
The first tonal pull request! Thanks

**Comment by AdrienFromToulouse** [comment]
you are doing a great job by the way!

**Comment by danigb** [comment]
Thanks! Can I ask you a question? Today more than 100 people starred this repo... do you know why?

**Comment by AdrienFromToulouse** [comment]
sure! check this out! https://www.reddit.com/r/javascript

**Comment by danigb** [comment]
Thanks! I did know about bandlab.com, but i didn't try it before.... it looks awesome!! Congrats!

**Pull request merged**
