### PR TITLE
Update scales.json

### PR DESCRIPTION
**Pull request by gabrocheleau**
Added a few scales, changed the order to correspond to melodic minor modes and changed the main name of some other scales to reflect the most commonly used.

### CODE REVIEW

**Comment by m-emm** [comment]
@gabrocheleau  this is a great suggestion. I was also missing the half-full/symmetrical diminished scale.
https://www.thejazzresource.com/symmetrical_diminished.html

I would very much enjoy if this pull request would be included into tonal.
However it might be tough because you are changing the api by changing the names of scales. Maybe some users of the library are already relying on the fact that "diminished" refers to the whole-half scale and not the half-whole. My suggestion: 
* leave the previous name ("diminished") to still point to the whole-half scale, so existing users of this scale are not affected by your change
* add the name "whole-half diminished" as alias for this existing scale, this gives more clarity
* add the new half-whole scale with the name "symmetrical diminished"
* add an alias for this new scale to be ""half-whole diminished"

What do you think? Do any other users have opinions on that?

**Comment by gabrocheleau** [comment]
@m-emm Great input! I've reverted back the name of the diminished scale with the compatibility issue in mind, and added whole-half as an alias. However, it doesn't seem clear to me that the name "symmetrical diminished" is an accepted name for "half-whole diminished", so I think it might be best to use "half-whole diminished". I've  seen the name "dominant diminished" used quite often for the half-whole (as it fits over a Dominant b9 chord), so I've added that name as an alias.

**Comment by m-emm** [comment]
I‘m glad I could help. Regarding „symmetrical Diminished“: I came across this in an online course of Berklee College. Now I wanted to give a reference to literature to support my point. I opened my copy of „Mulholland, Hojnacki : The Berklee Book of Jazz harmony“. They dedicate a whole page (p. 162) to the „Symmetric Diminished“ scale (aha my firs mistake „symmetric“ not „symmetrical“) - but looking at it in this book this decribes the whole-half scale, sorry I was wrong here. In the same book on p. 36 they explain the „Symmetric Dominant Scale“- and this is the half-whole scale, the same as your alternative name.

So the way you suggest seems good to me. I‘m looking forward to being able to use this scale in tonal - thanks for helping to improve one of my favourite libraries.

**Comment by danigb** [comment]
Thanks for the PR! 👍 Although scales.json file needs some good refactor (see https://github.com/danigb/tonal/pull/56) this is a good improvement. 

(and sorry for the delay, I've been quite busy lately...)

**Pull request merged**
