### PR TITLE
tonal-array typescript migration

### PR DESCRIPTION
**Pull request by rakannimer**
Hey ! 

This pull request converts tonal-array from js to typescript and integrates the conversion with the existing build .

As discussed in #68, here's a minimal proposal to get us started on the ts migration. 

Things I tried before settling with this solution : 

1. Add typescript to the rollup build pipeline (Lerna and aliases integration with ts was not an enjoyable experience).
2. Isolate each package build process and change incrementally to use typescript. (Too much code added. Felt like overkill.)

This solution : 

Add a typescript compiler build step at the root of the monorepo that ignores js and compiles ts to js and emits to the same location the ts file is in, allowing the normal build process to work as usual. 

The step is ran before : `test` and `build` scripts

This PR looks big because it also has types definitions. But the relevant code
with the minimum viable changes for the migration can be found in this commit : https://github.com/danigb/tonal/commit/4c089ac2a6483fe6f316a9d40aac0499f8ba4019 and is quite small.

If you like this solution, I  can get started on the rest of the packages and finalize the types. 

Let me know what you think :) 

Cheers !

### CODE REVIEW

**Comment by danigb** [comment]
Thanks a lot! I'll review both your PRs this night! 🙏 🎉

**Comment by danigb** [comment]
Hi! Starting the review, I've notice some changes in the format style of the code. So I've updated the infrastructure to run the same version of prettier in every commit. Can you rebase your both PRs with master to add that changes?

Thanks! 🙏 

Tomorrow I'll review this PR with calm... I know rollup and lerna are complex (sometimes I want to get rid of them!)... Thanks for the work 👍

**Comment by rakannimer** [comment]
Hey, my workspace is getting kind of messy, do you mind if we close this PR for now while waiting for #68 ? 

After that I'll open a fresh one and start again from latest on master.

Cheers !

**Comment by danigb** [comment]
Yes! No problem... sorry for the mess! 🙏

**Comment by danigb** [comment]
I'd recommend starting with Note module (because it's the one with no dependencies at all), and then Interval (that uses types from Note). Then, the rest...

**Comment by rakannimer** [comment]
Noted ! (No pun intended 😅)

Will open up a PR tomorrow for Note Module and we'll start from there !

Thanks for your time ! Cheers !

**Pull request closed without merging**
